Index page #1
bearwithtornhands/airbnb-demo-frontend pull request #2
Opened 2018-01-04 19:56 UTC by bearwithtornhands

Главная страница с адаптивом. 
ps: элементы слайдеров на адаптиве сделал обычным списком. Думаю, что выстраиванием их в линию будет заниматься компонент слайдера.

2018-01-05 12:44 UTC, evgenyrodionov commented
Настрой гит и гитхаб

2018-01-05 12:47 UTC, imevro requested changes
читай частые ошибки, ты видимо их вообще не открывал. дальше не проверял

2018-01-05 12:47 UTC, evgenyrodionov commented on public/index.html
> +  <title>React App</title>
смени

2018-01-05 12:47 UTC, evgenyrodionov commented on src/App.js
> +import Header from "./components/header/Header";
читай частые ошибки — зачем такая вложенность? 

и зачем директория компонентс, если все приложение построено на компонентах?

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +  margin: -18px -9px 0;
отрицательные марджины зло

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +const Cell = styled.div`
целл-хуел, вообще неочевидный нейминг

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +const Image = styled.div`
имейдж это див? это как вообще?

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +  img {
нельзя так делать — что за стилизация по тегу

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +const Title = styled.div`
тайтл это див?

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +  border-top-left-radius: 0;
зачем это задавать если по-умолчанию их и так нет?

2018-01-05 12:47 UTC, evgenyrodionov commented on src/components/category/Category.js
> +  background: white;
зачем?

2018-01-05 19:20 UTC, bearwithtornhands commented
Поправил email в git config проекта. Убрал лишнюю вложенность директорий. Поправил имена некоторых компонентов. Добавил fbg2 вместо своей сетки.

2018-01-06 14:30 UTC, imevro requested changes

2018-01-06 14:30 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
смени

2018-01-06 14:30 UTC, evgenyrodionov commented on src/App.js
> +      <div className="App">
зачем тебе этот класснейм?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/Copy/index.js
> +const Copy = styled.div`
почему текст дивом?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/Menu.js
> +const Menu = styled.div`
nav?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/Nav.js
> +const Nav = styled.div`
нав = див?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/Nav.js
> +        <MenuColumn>
чё-то у тебя дохуя вложенности

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/SelectParams/index.js
> +  -webkit-appearance: none;
в ск есть автопрефиксер

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/SelectParams/index.js
> +          <Select>
1) что за вложенность
2) селект селект селект селект селект селект селект селект селект селект селект селект что с вёрсткой?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/Social/index.js
> +  background-image: url(${tw});
почему не img тег, зачем через бэкграунд?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/index.js
> +const FooterBody = styled.div`
ты и так в футере, зачем столько префиксов футер футер футер футер?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/Footer/index.js
> +const FooterFoot = styled.div`
футерфут?

2018-01-06 14:30 UTC, evgenyrodionov commented on src/index.css
> +  outline: none;
outlinenone.com

2018-01-07 17:17 UTC, imevro approved these changes

2018-01-07 17:18 UTC, merged