Filter
bearwithtornhands/airbnb-demo-frontend pull request #4
Opened 2018-01-26 08:40 UTC by bearwithtornhands

now: https://build-edimrkmcxj.now.sh

2018-01-26 13:31 UTC, evgenyrodionov commented
Давай цену тоже будем показывать
![image](https://user-images.githubusercontent.com/775692/35441875-4748f05a-02b6-11e8-94e6-93980ecda2c7.png)

Год не нужно показывать и месяц давай более читаемым (13 Jan — 28 Feb)
![image](https://user-images.githubusercontent.com/775692/35441883-4e50eb8c-02b6-11e8-8a78-9e9c5cb0f366.png)

2018-01-26 13:33 UTC, imevro requested changes

2018-01-26 13:33 UTC, evgenyrodionov commented on src/UI/Checkbox/index.js
> +    const code = nanoid(4);
а зачем? заведи стабильный

2018-01-26 13:33 UTC, evgenyrodionov commented on src/UI/Checkbox/index.js
> +  handleClick = event => {
а зачем тут класс? ты же никак не используешь стейт или лайфсайкл

2018-01-26 13:33 UTC, evgenyrodionov commented on src/UI/DropDown/index.js
> +            <BodyMiddle fixed={isOpen}>
чё-то выглядит как хак

2018-01-26 22:06 UTC, bearwithtornhands commented
now: https://build-qbcjbnbvpe.now.sh

2018-01-26 22:06 UTC, bearwithtornhands commented
now: https://build-qbcjbnbvpe.now.sh

2018-01-27 08:34 UTC, bearwithtornhands commented
now: https://build-mlerokizvi.now.sh

2018-01-27 13:02 UTC, evgenyrodionov commented
Контент фильтра уезжает дальше чем нужно 

![image](https://user-images.githubusercontent.com/775692/35472180-5cbe9492-037b-11e8-9132-3157f634331f.png)
![image](https://user-images.githubusercontent.com/775692/35472182-6626efb6-037b-11e8-9db5-8e3f635fd2f4.png)

2018-01-27 13:10 UTC, imevro requested changes

2018-01-27 13:10 UTC, evgenyrodionov commented on src/UI/DropDown/index.js
> +          <StyledBody large={name === "more"} fixed={isOpen}>
ебать костылей ты наплодил, а что тебе мешало просто отдельный дропдаун сделать для More Filters?

2018-01-27 13:10 UTC, evgenyrodionov commented on src/Homes/Filter.js
> +  handleCheckboxsChange = (name, id, checked) => {
а давай попробуем вот все эти методы упростить до `onChange = (...) => ...`

2018-01-27 18:12 UTC, bearwithtornhands commented
airbnb-demo.now.sh/

2018-01-27 18:23 UTC, bearwithtornhands commented
airbnb-demo.now.sh/homes

2018-01-28 18:48 UTC, imevro requested changes

2018-01-28 18:48 UTC, evgenyrodionov commented on src/Homes/Filter.js
> +        ...this.state,
это не нужно делать, реакт обновляет только указанные ключи, а остальные не трогают

2018-01-28 18:48 UTC, evgenyrodionov commented on src/Homes/Filter.js
> +        typeof values === "object" ? { ...this.state[name], ...values } : values
выглядит как хак

2018-01-28 18:48 UTC, evgenyrodionov commented on src/Homes/Filter.js
> +const MoreFiltersDifference = (state, defaultState) => {
это компонент? что за странный нейминг?

2018-01-29 21:04 UTC, imevro approved these changes

2018-01-29 21:04 UTC, merged